package config

import (
	"fmt"
	"os"
	"strings"
)

// CopyConfigWithHelp reads a config file, adds usage help comments, and writes it to the destination
func CopyConfigWithHelp(sourcePath, destPath string, encryptEnabled bool, encryptionReceiver string) error {
	// Read the source config
	data, err := os.ReadFile(sourcePath)
	if err != nil {
		return fmt.Errorf("error reading source config file: %w", err)
	}

	// Convert to string for easier manipulation
	content := string(data)

	// Prepare the help comments
	var helpComments string

	// Basic usage information
	helpComments = "# GO-BACKUP USAGE INFORMATION\n"
	helpComments += "# ------------------------\n"
	helpComments += "# This file was automatically generated by go-backup.\n"
	helpComments += "# It contains configuration settings for restoring this backup.\n"
	helpComments += "#\n"
	helpComments += "# Installation:\n"
	helpComments += "#   To install go-backup:\n"
	helpComments += "#   1. Visit: https://github.com/kennycyb/go-backup\n"
	helpComments += "#   2. Or use: go install github.com/kennycyb/go-backup@latest\n"
	helpComments += "#\n"

	// Add encryption-specific comments if encryption was enabled
	if encryptEnabled {
		helpComments += "# Decryption:\n"
		helpComments += "#   This backup was encrypted using GPG.\n"
		helpComments += fmt.Sprintf("#   Recipient: %s\n", encryptionReceiver)
		helpComments += "#   To decrypt manually:\n"
		helpComments += "#     gpg --output backup.tar.gz --decrypt backup.tar.gz.gpg\n"
		helpComments += "#\n"
		helpComments += "#   Or let go-backup handle decryption:\n"
		helpComments += "#     go-backup restore --file backup.tar.gz.gpg\n"
		helpComments += "#\n"
	}

	helpComments += "# Restore Command:\n"
	helpComments += "#   go-backup restore --file [BACKUP_FILE] --target [DESTINATION]\n"
	helpComments += "#\n"
	helpComments += "# For more options:\n"
	helpComments += "#   go-backup restore --help\n"
	helpComments += "#\n"

	// Insert our help comments after the first comment block
	if strings.HasPrefix(content, "#") {
		// Find the end of the first comment block
		lines := strings.Split(content, "\n")
		firstNonComment := 0
		for i, line := range lines {
			if !strings.HasPrefix(strings.TrimSpace(line), "#") && strings.TrimSpace(line) != "" {
				firstNonComment = i
				break
			}
		}

		// Insert our help comments after the first comment block
		updatedContent := strings.Join(lines[:firstNonComment], "\n") + "\n" +
			helpComments +
			strings.Join(lines[firstNonComment:], "\n")

		// Write to the destination file
		return os.WriteFile(destPath, []byte(updatedContent), 0644)
	} else {
		// If there's no comment block, just prepend our help
		updatedContent := helpComments + content
		return os.WriteFile(destPath, []byte(updatedContent), 0644)
	}
}
